# Generated by Django 3.2.7 on 2021-09-25 04:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runusers',
            old_name='timestamp',
            new_name='timestamp_added',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='data_metadata',
        ),
        migrations.AddField(
            model_name='certificate',
            name='timestamp_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Metadata about uploaded data.', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='timestamp_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='timestamp_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='run',
            name='state',
            field=models.CharField(choices=[('D', 'Draft'), ('O', 'Open'), ('C', 'Closed'), ('P', 'Private')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='runusers',
            name='timestamp_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Metadata about submission.', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='timestamp_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='timestamp_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
