# Generated by Django 3.2.6 on 2021-08-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='require_submission',
        ),
        migrations.AddField(
            model_name='lecture',
            name='require_submission',
            field=models.BooleanField(default=False, help_text='Next chapter wont be unlocked until submission is provided.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='length',
            field=models.IntegerField(default=7, help_text='Number of days that chapter will be open. If all chapters length is set to 0 course is considered self-paced.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='state',
            field=models.CharField(choices=[('D', 'Draft'), ('O', 'Open'), ('C', 'Closed'), ('P', 'Private')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='description',
            field=models.TextField(blank=True, help_text='Introduce the study material, explain what data are uploaded.', null=True),
        ),
    ]
