# Generated by Django 3.2.7 on 2021-09-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='video',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
