# Generated by Django 3.2.6 on 2021-08-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210803_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecture_type',
            field=models.CharField(choices=[('V', 'Video Lesson'), ('T', 'Text to read'), ('PF', 'Peer Feedback'), ('P', 'Project'), ('F', 'Feedback')], default='V', max_length=2),
        ),
        migrations.AddField(
            model_name='lecture',
            name='subtitle',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='data',
            field=models.FileField(blank=True, help_text='Upload study material (document, video, image).', null=True, upload_to=''),
        ),
    ]
