# Generated by Django 3.2.6 on 2021-08-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210803_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='require_submission_certificate',
            field=models.BooleanField(default=False, help_text='The course certificate wont be unlocked until submission is provided.'),
            preserve_default=False,
        ),
    ]
