# Generated by Django 4.0.1 on 2022-02-08 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20220110_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='Question')),
                ('answer', models.TextField(help_text='Full description of the question.', verbose_name='Description')),
                ('order', models.IntegerField(default=0, help_text='Order number for the question.')),
                ('state', models.CharField(choices=[('D', 'Draft'), ('C', 'Course'), ('S', 'Subscribed Course'), ('B', 'Both')], default='D', max_length=1, verbose_name='State')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Course')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.run', verbose_name='Run')),
            ],
            options={
                'verbose_name': 'Frequently asked question',
                'verbose_name_plural': 'Frequently asked questions',
            },
        ),
    ]
