# Generated by Django 3.2.6 on 2021-08-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lecture_require_submission_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='chapter',
        ),
        migrations.AddField(
            model_name='lecture',
            name='require_submission_review',
            field=models.BooleanField(default=False, help_text='Submission is accepted only after being accepted by a review.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='accepted',
            field=models.BooleanField(default=True, help_text='Check if the submission if acceptable. If not, the reviewee will have to submit a new submission.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(blank=True, help_text='Describe your opinion about the submission.', null=True),
        ),
    ]
