# Generated by Django 3.2.6 on 2021-08-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210803_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='require_submission_certificate',
            new_name='require_submission_for_certificate',
        ),
    ]
