# Generated by Django 3.2.8 on 2022-02-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20220210_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_length',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='required_skills',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
