# Generated by Django 3.2.6 on 2021-08-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_require_submission_certificate_lecture_require_submission_for_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='require_submission_for_certificate',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='require_submission',
            field=models.CharField(choices=[('N', 'Not required'), ('C', 'Required for next chapter'), ('E', 'Required to end course')], default='N', max_length=1),
        ),
    ]
