# Generated by Django 3.2.8 on 2022-02-26 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20220217_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runusers',
            name='subscription_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.subscriptionlevel', verbose_name='Subscription Level'),
        ),
    ]
