# Generated by Django 3.2.6 on 2021-08-03 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210803_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_type',
            field=models.CharField(choices=[('V', 'Video Lesson'), ('T', 'Text to read'), ('PF', 'Peer Feedback'), ('P', 'Project'), ('F', 'Feedback'), ('L', 'Live lesson')], default='V', max_length=2),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('link', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lecture')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.run')),
            ],
        ),
    ]
