# Generated by Django 3.2.6 on 2021-08-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20210803_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='require_submission',
            field=models.CharField(choices=[('N', 'Not required'), ('C', 'Required for next chapter'), ('E', 'Required to end course')], default='N', help_text='A submission can be required either for continuing to the next chapter or to finish the course.', max_length=1),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='require_submission_review',
            field=models.CharField(choices=[('N', 'Not required'), ('C', 'Required for next chapter'), ('E', 'Required to end course')], default='N', help_text='Submission is accepted only after being accepted by a review.', max_length=1),
        ),
    ]
