# Generated by Django 3.2.8 on 2022-04-21 21:20

import courses.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_runusers_subscription_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='public_submission',
            field=models.BooleanField(default=False, verbose_name='Make submissions public within Group'),
        ),
        migrations.AddField(
            model_name='run',
            name='allow_public_submission',
            field=models.BooleanField(default=False, verbose_name='Allow public submissions within Group (has to be set per course lecture)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='image',
            field=models.FileField(blank=True, help_text='Upload an image of your work.', null=True, upload_to='submissions', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg']), courses.validators.FileSizeValidator(2)], verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='submission',
            name='video_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Video link'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='data',
            field=models.FileField(blank=True, help_text='Upload an attachment.', null=True, upload_to='submissions', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'pdf', 'doc', 'docx', 'txt', 'hex']), courses.validators.FileSizeValidator(2)], verbose_name='Attachment'),
        ),
    ]
