# Generated by Django 3.2.6 on 2021-08-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20210803_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='limit',
            field=models.IntegerField(default=0, help_text='Max number of attendees, after which registration for the Run will close. If set to 0 the course will have no limit.'),
        ),
    ]
