# Generated by Django 3.2.8 on 2022-04-22 20:14

import courses.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20220421_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='data',
            field=models.FileField(blank=True, help_text='Field not used for now. Please ignore it.', null=True, upload_to='certificates', validators=[django.core.validators.FileExtensionValidator(['pdf']), courses.validators.FileSizeValidator(2)], verbose_name='Data'),
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Only for informational admin purposes, this field is not shown on the certificate', max_length=250, verbose_name='Title')),
                ('html', models.TextField(help_text='HTML template of the Certificate', verbose_name='HTML')),
                ('timestamp_added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('timestamp_modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('intended_course', models.ForeignKey(blank=True, help_text='Only for informational admin purposes, can be used by multiple courses or none', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='Intended course')),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.certificatetemplate'),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.certificatetemplate'),
        ),
    ]
