# Generated by Django 3.2.8 on 2022-05-24 08:02

import courses.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20220423_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='data',
            field=models.FileField(blank=True, help_text='Upload an attachment.', null=True, upload_to='submissions', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'pdf', 'doc', 'docx', 'txt', 'hex', 'zip']), courses.validators.FileSizeValidator(2)], verbose_name='Attachment'),
        ),
    ]
