# Generated by Django 3.2.8 on 2022-05-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_submission_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='runusers',
            name='note',
            field=models.TextField(blank=True, help_text='Visible only to admins', null=True, verbose_name='Note'),
        ),
    ]
