# Generated by Django 3.2.13 on 2022-07-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_runusers_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='runusers',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Metadata about meeting.', null=True, verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='runusers',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
