# Generated by Django 3.2.8 on 2022-10-07 22:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20220729_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_allowed', models.BooleanField(default=False, verbose_name='Allow PayPal payments')),
                ('paypal_base_url', models.URLField(blank=True, max_length=250, null=True, verbose_name='PayPal Base URL')),
                ('paypal_client_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='PayPal Client ID')),
                ('paypal_secret', models.CharField(blank=True, max_length=250, null=True, verbose_name='PayPal Secret')),
                ('paypal_currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='PayPal Currency')),
                ('bank_transfer_allowed', models.BooleanField(default=False, verbose_name='Allow bank transfer payments')),
                ('bank_transfer_bank_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Bank Name')),
                ('bank_transfer_account_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Bank Account Name')),
                ('bank_transfer_iban', models.CharField(blank=True, max_length=250, null=True, verbose_name='Bank IBAN')),
                ('bank_transfer_swift', models.CharField(blank=True, max_length=250, null=True, verbose_name='Bank SWIFT')),
                ('bank_transfer_currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='Bank Currency')),
                ('company_name', models.CharField(max_length=250, verbose_name='Company name')),
                ('company_street', models.CharField(max_length=250, verbose_name='Company Street')),
                ('company_post_code', models.CharField(max_length=250, verbose_name='Company Post Code')),
                ('company_city', models.CharField(max_length=250, verbose_name='Company City')),
                ('company_country', models.CharField(max_length=250, verbose_name='Company Country')),
                ('company_id', models.CharField(max_length=250, verbose_name='Company ID')),
                ('company_tax_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Tax Number')),
                ('company_vat_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='VAT Number')),
                ('company_mail', models.CharField(max_length=250, verbose_name='Company Email')),
                ('company_phone', models.CharField(max_length=20, verbose_name='Company Phone')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='payment_profiles/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('company_note', models.CharField(blank=True, max_length=250, null=True, verbose_name='Invoice Company Note')),
                ('footer_note', models.CharField(blank=True, max_length=500, null=True, verbose_name='Invoice Footer Note')),
                ('vat_rate', models.IntegerField(default=0, verbose_name='VAT rate')),
            ],
        ),
        migrations.AlterField(
            model_name='runusers',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Metadata about RunUser.', null=True, verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='course',
            name='payment_profile',
            field=models.ForeignKey(blank=True, help_text='Contains Invoicing and Payment details for paid courses.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.paymentprofile', verbose_name='Payment Profile'),
        ),
    ]
