# Generated by Django 3.2.8 on 2022-10-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20220729_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runusers',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Metadata about RunUser.', null=True, verbose_name='Metadata'),
        ),
    ]
