# Generated by Django 3.2.8 on 2022-10-14 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('courses', '0017_auto_20221013_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='payment_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.paymentprofile'),
        ),
    ]
