# Generated by Django 3.2.7 on 2022-10-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_run_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(default=0, help_text='Order number for the Chapter in the Course.'),
        ),
    ]
