# Generated by Django 3.2.7 on 2022-11-12 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0022_auto_20221109_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='courses.run', verbose_name='Run'),
        ),
        migrations.AlterField(
            model_name='course',
            name='creator',
            field=models.ForeignKey(help_text='Creator of the course, mainly responsible for the content', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='emailtemplateimage',
            name='creator',
            field=models.ForeignKey(help_text='Uploader of the image.', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.run', verbose_name='Run'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='leader',
            field=models.ForeignKey(blank=True, help_text='Leader of the meeting, eg. lecturer, vip...', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader', to=settings.AUTH_USER_MODEL, verbose_name='Leader'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='organizer',
            field=models.ForeignKey(help_text='Organizer of the meeting, responsible for the meeting.', on_delete=django.db.models.deletion.RESTRICT, related_name='organizer', to=settings.AUTH_USER_MODEL, verbose_name='Organizer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='run',
            name='manager',
            field=models.ForeignKey(help_text='Manager of the course run, responsible for the smoothness of the run.', on_delete=django.db.models.deletion.RESTRICT, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='runusers',
            name='subscription_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.subscriptionlevel', verbose_name='Subscription Level'),
        ),
        migrations.AlterField(
            model_name='subscriptionlevel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='subscriptionlevel',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.run', verbose_name='Run'),
        ),
    ]
